apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: librairy
type: kubernetes.io/tls
data:
  # Remplacer par le contenu base64 de file.crt et file.key
  # kubectl create secret tls tls-secret --cert=certs/file.crt --key=certs/file.key -n librairy --dry-run=client -o yaml
  tls.crt: ""  # base64 de file.crt
  tls.key: ""  # base64 de file.key
