apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecommerce
  namespace: argocd
spec:
  description: E-Commerce DevSecOps Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: ecommerce
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
